{{- if .Values.imageCredentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inspect.fullname" . }}-registry-cred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
