# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: "Zora"
site_url: https://zora.undistro.io/docs
repo_url: https://github.com/undistro/zora
repo_name: undistro/zora
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
plugins:
  - search
  - mike:
      version_selector: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  version:
    provider: mike

nav:
  - Documentation:
      - Introduction: index.md
      - Install: install.md
      - Prepare the target cluster: target-cluster.md
      - Connect the target cluster to Zora: connect-cluster.md
      - Configure a cluster scan: cluster-scan.md
      - Glossary: glossary.md
  - Helm Chart:
      - Zora Helm Chart: helm-chart.md
