{{- if .Values.operator.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}
  labels:
    {{- include "inspect.operatorLabels" . | nindent 4 }}
  {{- with .Values.operator.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
{{- if .Values.operator.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}-leader-election
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs/status
    verbs:
      - get
  - apiGroups:
      - inspect.undistro.io
    resources:
      - clusters
      - clusterissues
      - clusterscans
      - plugins
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - inspect.undistro.io
    resources:
      - clusters/finalizers
      - clusterscans/finalizers
    verbs:
      - update
  - apiGroups:
      - inspect.undistro.io
    resources:
      - clusters/status
      - clusterscans/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}-proxy
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "inspect.operatorServiceAccountName" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "inspect.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "inspect.operatorServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "inspect.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "inspect.operatorServiceAccountName" . }}-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "inspect.operatorServiceAccountName" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ include "inspect.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
