# permissions for end users to edit clusterissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissue-editor-role
rules:
- apiGroups:
  - inspect.undistro.io
  resources:
  - clusterissues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inspect.undistro.io
  resources:
  - clusterissues/status
  verbs:
  - get
