# permissions for end users to edit customchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zora
    app.kubernetes.io/managed-by: kustomize
  name: customcheck-editor-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - customchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - customchecks/status
  verbs:
  - get
