# permissions for end users to view plugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin-viewer-role
rules:
- apiGroups:
  - inspect.undistro.io
  resources:
  - plugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inspect.undistro.io
  resources:
  - plugins/status
  verbs:
  - get
