# permissions for end users to view vulnerabilityreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zora
    app.kubernetes.io/managed-by: kustomize
  name: vulnerabilityreport-viewer-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - vulnerabilityreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - vulnerabilityreports/status
  verbs:
  - get
