# permissions for end users to view customchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customcheck-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zora
    app.kubernetes.io/part-of: zora
    app.kubernetes.io/managed-by: kustomize
  name: customcheck-viewer-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - customchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - customchecks/status
  verbs:
  - get
