# permissions for end users to edit clusterissueoverrides.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissueoverride-editor-role
rules:
- apiGroups:
  - zora.undistro.io
  resources:
  - clusterissueoverrides
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - zora.undistro.io
  resources:
  - clusterissueoverrides/status
  verbs:
  - get
