apiVersion: inspect.undistro.io/v1alpha1
kind: Plugin
metadata:
  name: popeye
spec:
  image: registry.undistro.io/dockerhub/derailed/popeye:v0.10.0
  command:
    - /bin/sh
    - -c
    - |
      start=$(date +%s)
      echo Scanning...
      /bin/popeye \
        -o json \
        --kubeconfig $(KUBECONFIG) \
        --all-namespaces \
        --force-exit-zero \
        > $(DONE_DIR)/results.json
      echo $(DONE_DIR)/results.json > $(DONE_DIR)/done
      ls -lh $(DONE_DIR)/
      end=$(date +%s)
      echo "Scan has finished in $(($end-$start)) seconds"
