apiVersion: zora.undistro.io/v1alpha2
kind: CustomCheck
metadata:
  labels:
    app.kubernetes.io/name: zora
    app.kubernetes.io/managed-by: kustomize
  name: custom-002
spec:
  message: "Required labels"
  severity: Low
  category: Custom
  match:
    resources:
      - group: ""
        version: v1
        resource: pods
  params:
    requiredLabels:
      - app
  variables:
    - expression: "'exempt' in object.metadata.labels && object.metadata.labels['exempt'] == 'true'"
      name: exempt
  validations:
    - expression: >
        variables.exempt ||
        !object.metadata.labels.all(label, 
          params.requiredLabels.all(
            req, req != label
          )
        )
      message: "Pod without required labels"
