apiVersion: zora.undistro.io/v1alpha1
kind: Plugin
metadata:
  labels:
    app.kubernetes.io/name: plugin
    app.kubernetes.io/instance: marvin
    app.kubernetes.io/part-of: zora
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zora
  name: marvin
spec:
  image: ghcr.io/undistro/marvin:v0.1.4
  resources:
    limits:
      cpu: 500m
      memory: 100Mi
  command:
    - /bin/sh
    - -c
    - |
      start=$(date +%s)
      echo Scanning...
      /marvin scan --disable-annotation-skip -o json -v 2 --kubeconfig $(KUBECONFIG) > $(DONE_DIR)/results.json
      exitcode=$(echo $?)
      if [ $exitcode -ne 0 ]; then
        echo "ERROR" > $(DONE_DIR)/error
      else
        echo $(DONE_DIR)/results.json > $(DONE_DIR)/done
      fi
      ls -lh $(DONE_DIR)/
      end=$(date +%s)
      echo "Scan has finished in $(($end-$start)) seconds with exit code $exitcode"
      exit $exitcode
