apiVersion: zora.undistro.io/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: clusterscan
    app.kubernetes.io/instance: mycluster
    app.kubernetes.io/part-of: zora
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: zora
  name: mycluster
spec:
  clusterRef:
    name: mycluster
  schedule: "*/2 * * * *"
