apiVersion: zora.undistro.io/v1alpha1
kind: CustomCheck
metadata:
  labels:
    app.kubernetes.io/name: zora
    app.kubernetes.io/managed-by: kustomize
  name: custom-001
spec:
  message: "Replicas limit"
  severity: Medium
  category: Custom
  match:
    resources:
      - group: apps
        version: v1
        resource: deployments
  validations:
    - expression: >
        object.spec.replicas <= 5
      message: "Deployment with more than 5 replicas"
