apiVersion: zora.undistro.io/v1alpha1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: zora
    app.kubernetes.io/managed-by: kustomize
  name: mycluster-vuln
spec:
  clusterRef:
    name: mycluster
  schedule: "*/10 * * * *"
  successfulScansHistoryLimit: 1
  plugins:
    - name: trivy
