apiVersion: zora.undistro.io/v1alpha1
kind: ClusterIssue
metadata:
  labels:
    category: Security
    cluster: mycluster
    id: M-102
    plugin: marvin
    scanID: b8622b8b-8be0-444c-8aaa-d67d3ac7bfd3
    severity: High
  name: mycluster-m-102-d67d3ac7bfd3
  namespace: zora-system
spec:
  category: Security
  cluster: mycluster
  id: M-102
  message: Privileged container
  resources:
    apps/v1/daemonsets:
      - kube-system/kube-proxy
    v1/pods:
      - kube-system/kube-proxy-ggxqd
  severity: High
  url: https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline
