{{- if .Values.nginx.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snitch.nginxServiceAccountName" . }}
  labels:
    {{- include "snitch.nginxLabels" . | nindent 4 }}
  {{- with .Values.nginx.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
