nameOverride: ""
fullnameOverride: ""

server:
  replicaCount: 1
  image: registry.undistro.io/snitch/server:v0.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 80
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

operator:
  image: registry.undistro.io/snitch/operator:v0.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  rbacProxy:
    image: registry.undistro.io/gcr/kubebuilder/kube-rbac-proxy:v0.8.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  metricsService:
    type: ClusterIP
    port: 8443
  monitor:
    enabled: false
  podAnnotations:
    kubectl.kubernetes.io/default-container: manager
  podSecurityContext:
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
  nodeSelector: {}
  affinity: {}
  tolerations: []
  serviceAccount:
    create: true
    annotations: {}
    name: ""
