# -- String to partially override fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override fullname template with a string
fullnameOverride: ""

imageCredentials:
  # -- Specifies whether the secret should be created by providing credentials
  create: true
  # -- Docker registry host
  registry: registry.undistro.io
  # -- Docker registry username
  username: ""
  # -- Docker registry password
  password: ""

# -- Specify docker-registry secret names as an array to be used when `imageCredentials.create` is false
imagePullSecrets: []

ingress:
  # -- Specifies whether the ingress should be created
  enabled: false
  # -- Ingress class name
  className: ""
  # -- Annotations to be added to ingress
  annotations: {}
  # kubernetes.io/tls-acme: "true"
  # -- The host of Snitch in ingress rule
  host: snitch.domain
  # -- `path` and `pathType` of API in ingress rule. `path` pattern may vary according ingress controller (`/api/*` for GCE, `/api/.*` for NCP)
  server:
    path: /api
    pathType: ImplementationSpecific
  # -- `path` and `pathType` of UI in ingress rule. `path` pattern may vary according ingress controller (`/*` for GCE, `/.*` for NCP)
  ui:
    path: /
    pathType: ImplementationSpecific
  # -- The name of secret which contains keys named: `tls.crt` - the certificate; `tls.key` - the private key
  tlsSecretName: ""

operator:
  # -- Number of replicas desired of Snitch operator
  replicaCount: 1
  image:
    # -- Snitch operator image repository
    repository: registry.undistro.io/snitch/operator
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  rbac:
    # -- Specifies whether ClusterRoles and ClusterRoleBindings should be created
    create: true
    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to be added to service account
      annotations: {}
      # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
      name: ""
  # -- Annotations to be added to pods
  podAnnotations:
    kubectl.kubernetes.io/default-container: manager
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsNonRoot: true
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to `manager` container
  securityContext:
    allowPrivilegeEscalation: false
  metricsService:
    # -- Type of metrics service
    type: ClusterIP
    # -- Port of metrics service
    port: 8443
  serviceMonitor:
    # -- Specifies whether a Prometheus `ServiceMonitor` should be enabled
    enabled: false
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to `manager` container
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  rbacProxy:
    image:
      # -- `kube-rbac-proxy` image repository
      repository: registry.undistro.io/gcr/kubebuilder/kube-rbac-proxy
      # -- `kube-rbac-proxy` image tag
      tag: v0.8.0
      # -- Image pull policy
      pullPolicy: IfNotPresent
    # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to `kube-rbac-proxy` container
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}

server:
  # -- Number of replicas desired of Snitch server
  replicaCount: 1
  image:
    # -- Snitch server image repository
    repository: registry.undistro.io/snitch/server
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  rbac:
    # -- Specifies whether ClusterRole and ClusterRoleBinding should be created
    create: true
    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to be added to service account
      annotations: {}
      # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
      name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext: {}
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 8080
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources: {}
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}

ui:
  # -- Number of replicas desired of Snitch UI
  replicaCount: 1
  image:
    # -- Snitch UI image repository
    repository: registry.undistro.io/snitch/ui
    # -- Overrides the image tag whose default is the chart appVersion
    tag: ""
    # -- Image pull policy
    pullPolicy: IfNotPresent
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to be added to service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext: {}
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 8080
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources: {}
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}

nginx:
  # -- Number of replicas desired of nginx
  replicaCount: 1
  # -- NGINX image
  image: registry.undistro.io/dockerhub/library/nginx:1.20.2
  # -- Image pull policy
  imagePullPolicy: IfNotPresent
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to be added to service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: ""
  # -- Annotations to be added to pods
  podAnnotations: {}
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the pod
  podSecurityContext:
    runAsUser: 10000
    fsGroup: 10000
  # -- [Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context) to add to the container
  securityContext: {}
  service:
    # -- Service type
    type: ClusterIP
    # -- Service port
    port: 80
  # -- [Resources](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) to add to the container
  resources: {}
  autoscaling:
    # -- Enable replica autoscaling settings
    enabled: false
    # -- Minimum replicas for the pod autoscaling
    minReplicas: 1
    # -- Maximum replicas for the pod autoscaling
    maxReplicas: 100
    # -- Percentage of CPU to consider when autoscaling
    targetCPUUtilizationPercentage: 80
    # -- Percentage of Memory to consider when autoscaling
    targetMemoryUtilizationPercentage: ""
  # -- [Node selection](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node) to constrain a Pod to only be able to run on particular Node(s)
  nodeSelector: {}
  # -- [Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration) for pod assignment
  tolerations: []
  # -- Map of node/pod [affinities](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration)
  affinity: {}
