apiVersion: v1
kind: ServiceAccount
metadata:
  name: snitch-controller-manager
  namespace: snitch-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snitch-leader-election-role
  namespace: snitch-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: snitch-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - snitch.undistro.io
    resources:
      - clusters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - snitch.undistro.io
    resources:
      - clusters/finalizers
    verbs:
      - update
  - apiGroups:
      - snitch.undistro.io
    resources:
      - clusters/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snitch-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snitch-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snitch-leader-election-rolebinding
  namespace: snitch-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snitch-leader-election-role
subjects:
  - kind: ServiceAccount
    name: snitch-controller-manager
    namespace: snitch-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snitch-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snitch-manager-role
subjects:
  - kind: ServiceAccount
    name: snitch-controller-manager
    namespace: snitch-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snitch-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: snitch-proxy-role
subjects:
  - kind: ServiceAccount
    name: snitch-controller-manager
    namespace: snitch-system
