{{- if .Values.operator.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inspect.fullname" . }}-metrics-monitor
  labels:
    {{- include "inspect.operatorLabels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      {{- include "inspect.operatorSelectorLabels" . | nindent 4 }}
{{- end }}
