name: Update docs
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. "v0.5")'
        type: string
        required: true
      latest:
        description: 'latest'
        type: boolean
      dev:
        description: 'dev'
        type: boolean
env:
  GIT_USER: "github-actions"
  GIT_EMAIL: "github-actions@github.com"
jobs:
  docs:
    name: Update docs ${{ inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Install MkDocs and Mike
        run: pip install mkdocs-material mike

      - name: Set 'latest' alias
        if: inputs.latest
        run: echo 'alias=latest' >> $GITHUB_ENV

      - name: Set 'dev' alias
        if: inputs.dev
        run: echo 'alias=dev' >> $GITHUB_ENV

      - name: Fetch gh-pages branch
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_USER"
          git fetch origin gh-pages --depth=1

      - name: Mike deploy
        run: |
          cp -f charts/zora/README.md docs/helm-chart.md
          cp -f charts/zora/values.yaml docs/values.yaml
          mike deploy --update-aliases ${{ inputs.version }} ${{ env.alias }}

      - name: Update titles and push
        run: |
          git checkout gh-pages
          go run update_titles.go
          git add versions.json
          git diff-index --quiet HEAD || git commit -m "update titles"
          git push origin gh-pages
