name: Package and Push Helm Chart

on:
  workflow_dispatch:
  push:
    tags:
      - "helm-chart-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  push-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        env:
          HELM_VERSION: v3.8.2
        run: |
          curl -sL "https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz" -o - | tar -xz
          mv linux-amd64/helm /usr/local/bin
          rm -r linux-amd64

      - name: Install helm-push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Package and push chart
        working-directory: ./charts
        env:
          HELM_REPO_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: helm cm-push inspect/ https://registry.undistro.io/chartrepo/library
