name: Update HML Environment
on:
  workflow_dispatch:
  push:
    tags:
      - "hml*"
jobs:
  build:
    uses: ./.github/workflows/docker-push.yaml
    secrets: inherit
  update_hml_environment:
    needs: build
    name: Update HML Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Helm
        env:
          HELM_VERSION: v3.8.2
        run: |
          curl -sL "https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz" -o - | tar -xz
          mv linux-amd64/helm /usr/local/bin
          rm -r linux-amd64

      - name: Add Undistro Helm repository
        run: helm repo add undistro "https://registry.undistro.io/chartrepo/library"
      - name: Update Undistro Helm repository
        run: helm repo update undistro

      - name: Get Chart version
        run: |
          echo "CHART_VERSION=$(
            helm search repo undistro/inspect | awk '/inspect/{print $2}'
          )" >> $GITHUB_ENV

      - name: Create kubeconfig file
        run: echo "${{ secrets.HML_KUBECONFIG }}" > /tmp/hml_kubeconfig.yaml

      - name: Get UI image tag
        run: |
          echo "UI_IMAGE_TAG=$(
            helm get values undistro-inspect -o yaml --kubeconfig /tmp/hml_kubeconfig.yaml | yq .ui.image.tag
          )" >> $GITHUB_ENV

      - name: Dry run
        run: |
          helm upgrade --install undistro-inspect undistro/inspect \
            -f charts/inspect/values-hml.yaml \
            --set imageCredentials.username=${{ secrets.REGISTRY_USERNAME }} \
            --set imageCredentials.password=${{ secrets.REGISTRY_PASSWORD }} \
            --set operator.image.tag=$GITHUB_REF_NAME \
            --set server.image.tag=$GITHUB_REF_NAME \
            --set scan.worker.image.tag=$GITHUB_REF_NAME \
            --set ui.image.tag=$UI_IMAGE_TAG \
            --version $CHART_VERSION \
            --namespace undistro-inspect \
            --create-namespace \
            --kubeconfig /tmp/hml_kubeconfig.yaml \
            --dry-run

      - name: Apply CRDs
        run: kubectl --kubeconfig=/tmp/hml_kubeconfig.yaml apply --recursive -f charts/inspect/crds/

      - name: Upgrade Helm release
        run: |
          helm upgrade --install undistro-inspect undistro/inspect \
            -f charts/inspect/values-hml.yaml \
            --set imageCredentials.username=${{ secrets.REGISTRY_USERNAME }} \
            --set imageCredentials.password=${{ secrets.REGISTRY_PASSWORD }} \
            --set operator.image.tag=$GITHUB_REF_NAME \
            --set server.image.tag=$GITHUB_REF_NAME \
            --set scan.worker.image.tag=$GITHUB_REF_NAME \
            --set ui.image.tag=$UI_IMAGE_TAG \
            --version $CHART_VERSION \
            --namespace undistro-inspect \
            --create-namespace \
            --kubeconfig /tmp/hml_kubeconfig.yaml
