name: Check Copyright License Header
on:
  pull_request:
    branches: [main]
jobs:
  license_check:
    name: Check Copyright License Header
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"
      - name: Call check-license target
        run: make check-license
