name: Publish Docker images and Helm chart
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write
  packages: write

env:
  CHARTS_REPOSITORY_PATH: charts.undistro.io
  CHART_PATH: charts/zora
  COMMIT_MESSAGE: "update zora chart"
  GIT_USER: "undistrobot"
  GIT_EMAIL: "undistro@getupcloud.com"

jobs:
  docker:
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  goreleaser:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    name: Update Helm repository
    runs-on: ubuntu-latest
    needs: [goreleaser]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout charts repository
        uses: actions/checkout@v3
        with:
          repository: undistro/charts.undistro.io
          ref: main
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }} # GITHUB_TOKEN is scoped to the current repository, so we need a PAT to checkout a different repository and commit on it.
          path: ${{ env.CHARTS_REPOSITORY_PATH }}

      - name: Sync charts
        run: rsync -avh --delete main/$CHART_PATH/ ${{ env.CHARTS_REPOSITORY_PATH }}/$CHART_PATH

      - name: Commit and push
        working-directory: ${{ env.CHARTS_REPOSITORY_PATH }}
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_USER"
          git add $CHART_PATH
          git status
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
          git push -u origin HEAD:main
